// Fleet orchestration for specialist shared-skill profiles.
// Profiles live under $FM_HOME/data/home-skills/<id>; home config/shared-skills
// is a generated projection. Sync engine remains reconcileHomeSkills.
//
// Profile inputs and target directories are preflighted fleet-wide before any
// write. Existing home state is then reconciled per target without rollback.

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
	FORBIDDEN_SPECIALIST_SKILL,
	SHARED_SKILLS_MANIFEST,
	checkHomeSkills,
	parseSkillManifestText,
	resolveHomeSkillsTarget,
	syncHomeSkills,
	validateSharedProfileNames,
} from "./home-skills";
import { atomicWriteFile } from "./managed-links";
import { isRealDirectory, isSymlink, normalizeExistingDir } from "./path-links";
import { parseSecondmateRegistryLine } from "./secondmate-registry";

const REPO_ROOT = fileURLToPath(new URL("../../../../", import.meta.url)).replace(/\/$/, "");
const PROFILE_REL = "home-skills";
const GENERATED_HEADER =
	"# Generated by fm home skills reconcile from data/home-skills/<id>. Do not edit.\n";

export type FleetTargetState =
	| "preflighted"
	| "preflight-failed"
	| "reconciled"
	| "reconcile-failed"
	| "validated"
	| "validate-failed"
	| "smoke-ok"
	| "smoke-failed"
	| "smoke-skipped";

export interface FleetTargetResult {
	id: string;
	home: string;
	states: FleetTargetState[];
	status: FleetTargetState;
	detail?: string;
	effectiveNames: string[];
}

export interface FleetReconcileResult {
	ok: boolean;
	targets: FleetTargetResult[];
	lines: string[];
}

export interface FleetReconcileOptions {
	target: string; // id or --all
	fmHome?: string;
	dataDir?: string;
	codeRoot?: string;
	/** Set false to skip OMP include/exclude smoke. Default: run when omp is on PATH. */
	smoke?: boolean;
	quiet?: boolean;
}

function envOr(name: string, fallback: string): string {
	const v = process.env[name];
	return v !== undefined && v !== "" ? v : fallback;
}

function emit(lines: string[], quiet: boolean | undefined, line: string): void {
	lines.push(line);
	if (!quiet) process.stdout.write(`${line}\n`);
}

function profilePath(dataDir: string, id: string): string {
	return join(dataDir, PROFILE_REL, id);
}

export function loadSharedSkillProfile(dataDir: string, id: string): string[] {
	const path = profilePath(dataDir, id);
	if (!existsSync(path) || isSymlink(path)) {
		throw Object.assign(new Error(`missing shared skill profile at ${path}`), { code: "profile-missing" });
	}
	return parseSkillManifestText(readFileSync(path, "utf8"), path);
}

export function materializeSharedManifest(home: string, id: string, names: string[]): string {
	const path = join(home, "config", SHARED_SKILLS_MANIFEST);
	const body = names.length ? `${names.join("\n")}\n` : "";
	const header = GENERATED_HEADER.replace("<id>", id);
	atomicWriteFile(path, `${header}${body}`);
	return path;
}

function listSecondmateIds(dataDir: string): Array<{ id: string; home: string }> {
	const reg = join(dataDir, "secondmates.md");
	if (!existsSync(reg)) {
		throw Object.assign(new Error(`secondmates registry not found at ${reg}`), { code: "missing-registry" });
	}
	const out: Array<{ id: string; home: string }> = [];
	for (const line of readFileSync(reg, "utf8").split(/\r?\n/)) {
		const entry = parseSecondmateRegistryLine(line);
		if (entry?.id && entry.home) out.push({ id: entry.id, home: entry.home });
	}
	return out;
}

function resolveTargets(
	target: string,
	opts: { fmHome: string; dataDir: string },
): Array<{ id: string; home: string }> {
	if (target === "--all") return listSecondmateIds(opts.dataDir);
	if (target.startsWith("-")) {
		throw Object.assign(new Error(`invalid reconcile target: ${target}`), { code: "invalid-target" });
	}
	if (target.startsWith("/") || target.startsWith("./") || target.startsWith("../") || isRealDirectory(target)) {
		throw Object.assign(new Error("reconcile requires a registry id or --all (not a bare path)"), {
			code: "invalid-target",
		});
	}
	const home = resolveHomeSkillsTarget(target, { fmHome: opts.fmHome, dataDir: opts.dataDir });
	return [{ id: target, home }];
}

function ompAvailable(): boolean {
	if (process.env.FM_HOME_SKILLS_SMOKE === "0") return false;
	const res = spawnSync("omp", ["--version"], { encoding: "utf8", timeout: 10_000 });
	return res.status === 0;
}

function validateDeterministic(
	home: string,
	opts: { codeRoot: string; fmHome: string; dataDir: string; quiet?: boolean },
): { ok: boolean; effectiveNames: string[]; detail?: string } {
	const check = checkHomeSkills(home, {
		quiet: true,
		codeRoot: opts.codeRoot,
		fmHome: opts.fmHome,
		dataDir: opts.dataDir,
	});
	if (!check.ok) return { ok: false, effectiveNames: check.effectiveNames, detail: check.status };
	const ompPath = join(home, "config", "omp.yml");
	const doc = Bun.YAML.parse(readFileSync(ompPath, "utf8")) as Record<string, unknown>;
	const skills = doc.skills as Record<string, unknown> | undefined;
	if (!skills || typeof skills !== "object") {
		return { ok: false, effectiveNames: check.effectiveNames, detail: "missing skills subtree" };
	}
	const include = Array.isArray(skills.includeSkills) ? (skills.includeSkills as string[]) : [];
	const expected = [...check.effectiveNames].sort();
	if (JSON.stringify(include) !== JSON.stringify(expected)) {
		return {
			ok: false,
			effectiveNames: check.effectiveNames,
			detail: `includeSkills drift: got ${include.join(",") || "-"} want ${expected.join(",") || "-"}`,
		};
	}
	if (expected.length === 0) {
		if (skills.enabled !== false) {
			return { ok: false, effectiveNames: check.effectiveNames, detail: "empty set requires skills.enabled false" };
		}
	} else if (skills.enabled !== true) {
		return { ok: false, effectiveNames: check.effectiveNames, detail: "nonempty set requires skills.enabled true" };
	}
	if (expected.includes(FORBIDDEN_SPECIALIST_SKILL)) {
		return { ok: false, effectiveNames: check.effectiveNames, detail: "forbidden sentinel in effective set" };
	}
	return { ok: true, effectiveNames: check.effectiveNames };
}

function runOmpSmoke(home: string, includeSkill: string | null): { ok: boolean; detail: string; skipped?: boolean } {
	if (!ompAvailable()) return { ok: true, detail: "omp unavailable or FM_HOME_SKILLS_SMOKE=0", skipped: true };
	const config = join(home, "config", "omp.yml");
	const exclude = FORBIDDEN_SPECIALIST_SKILL;
	let prompt: string;
	if (includeSkill) {
		prompt =
			`Read skill://${includeSkill}, then attempt to read skill://${exclude}. ` +
			`Output exactly SMOKE_OK only if the first succeeds and the second is unavailable; otherwise output SMOKE_FAIL.`;
	} else {
		prompt =
			`Attempt to read skill://${exclude}. Output exactly SMOKE_OK if the skill is unavailable; otherwise output SMOKE_FAIL.`;
	}
	const res = spawnSync(
		"omp",
		[
			"--thinking",
			"off",
			"--config",
			config,
			"--cwd",
			home,
			"--no-session",
			"--tools",
			"read",
			"--print",
			prompt,
		],
		{ encoding: "utf8", timeout: 120_000, env: process.env },
	);
	const out = `${res.stdout ?? ""}\n${res.stderr ?? ""}`;
	if (res.error) return { ok: false, detail: res.error.message };
	if (res.status !== 0) return { ok: false, detail: `omp exit ${res.status}: ${out.trim().slice(-400)}` };
	if (/\bSMOKE_OK\b/.test(out) && !/\bSMOKE_FAIL\b/.test(out)) return { ok: true, detail: "SMOKE_OK" };
	return { ok: false, detail: `smoke token missing: ${out.trim().slice(-400)}` };
}

function pushState(result: FleetTargetResult, state: FleetTargetState): void {
	result.states.push(state);
	result.status = state;
}

/**
 * Fleet reconcile: profile → materialize → sync → deterministic validate → OMP smoke.
 * Preflight profiles and target directories fleet-wide before writes; reconcile home state per target.
 */
export function reconcileFleet(opts: FleetReconcileOptions): FleetReconcileResult {
	const lines: string[] = [];
	const quiet = opts.quiet;
	const fmHome = opts.fmHome ?? envOr("FM_HOME", REPO_ROOT);
	const dataDir = opts.dataDir ?? envOr("FM_DATA_OVERRIDE", join(fmHome, "data"));
	const codeRootRaw = opts.codeRoot ?? envOr("FM_CODE_ROOT_OVERRIDE", envOr("FM_ROOT_OVERRIDE", REPO_ROOT));
	const codeRoot = normalizeExistingDir(codeRootRaw);
	if (!codeRoot) {
		emit(lines, quiet, "result=blocked:missing-code-root");
		return { ok: false, targets: [], lines };
	}

	let selected: Array<{ id: string; home: string }>;
	try {
		selected = resolveTargets(opts.target, { fmHome, dataDir });
	} catch (err) {
		const code = (err as { code?: string }).code ?? "error";
		emit(lines, quiet, `result=blocked:${code}`);
		if (!quiet) process.stderr.write(`error: ${err instanceof Error ? err.message : String(err)}\n`);
		return { ok: false, targets: [], lines };
	}

	emit(lines, quiet, `mode=reconcile`);
	emit(lines, quiet, `targets=${selected.map(t => t.id).join(",") || "-"}`);

	type Prepared = { id: string; home: string; names: string[] };
	const prepared: Prepared[] = [];
	const preflightFailed: FleetTargetResult[] = [];

	for (const t of selected) {
		const result: FleetTargetResult = {
			id: t.id,
			home: t.home,
			states: [],
			status: "preflight-failed",
			effectiveNames: [],
		};
		try {
			const homeNorm = normalizeExistingDir(t.home);
			if (!homeNorm) throw Object.assign(new Error(`home is not a directory: ${t.home}`), { code: "missing-home" });
			result.home = homeNorm;
			const names = loadSharedSkillProfile(dataDir, t.id);
			validateSharedProfileNames(codeRoot, names, `data/${PROFILE_REL}/${t.id}`);
			pushState(result, "preflighted");
			prepared.push({ id: t.id, home: homeNorm, names });
			emit(lines, quiet, `target=${t.id} state=preflighted shared=${names.join(",") || "-"}`);
		} catch (err) {
			const code = (err as { code?: string }).code ?? "error";
			const message = err instanceof Error ? err.message : String(err);
			pushState(result, "preflight-failed");
			result.detail = `${code}: ${message}`;
			preflightFailed.push(result);
			emit(lines, quiet, `target=${t.id} state=preflight-failed detail=${code}`);
			if (!quiet) process.stderr.write(`error: ${t.id}: ${message}\n`);
		}
	}

	if (preflightFailed.length) {
		emit(lines, quiet, "result=blocked:preflight");
		emit(lines, quiet, "note=zero writes; profile preflight failed for one or more targets");
		return { ok: false, targets: preflightFailed, lines };
	}

	const targets: FleetTargetResult[] = [];
	const wantSmoke = opts.smoke !== false;

	for (const p of prepared) {
		const result: FleetTargetResult = {
			id: p.id,
			home: p.home,
			states: ["preflighted"],
			status: "preflighted",
			effectiveNames: [],
		};
		emit(lines, quiet, `target=${p.id} home=${p.home}`);

		try {
			materializeSharedManifest(p.home, p.id, p.names);
			const sync = syncHomeSkills(p.home, {
				quiet: true,
				codeRoot,
				fmHome,
				dataDir,
			});
			if (!sync.ok) {
				pushState(result, "reconcile-failed");
				result.detail = sync.status;
				result.effectiveNames = sync.effectiveNames;
				emit(lines, quiet, `target=${p.id} state=reconcile-failed detail=${sync.status}`);
				targets.push(result);
				continue;
			}
			pushState(result, "reconciled");
			emit(lines, quiet, `target=${p.id} state=reconciled`);

			const validated = validateDeterministic(p.home, { codeRoot, fmHome, dataDir, quiet });
			result.effectiveNames = validated.effectiveNames;
			if (!validated.ok) {
				pushState(result, "validate-failed");
				result.detail = validated.detail;
				emit(lines, quiet, `target=${p.id} state=validate-failed detail=${validated.detail}`);
				targets.push(result);
				continue;
			}
			pushState(result, "validated");
			emit(lines, quiet, `target=${p.id} state=validated effective=${validated.effectiveNames.join(",") || "-"}`);

			if (!wantSmoke) {
				pushState(result, "smoke-skipped");
				emit(lines, quiet, `target=${p.id} state=smoke-skipped`);
				targets.push(result);
				continue;
			}
			const include =
				p.names[0] ??
				validated.effectiveNames.find(n => n !== FORBIDDEN_SPECIALIST_SKILL) ??
				null;
			const smoke = runOmpSmoke(p.home, include);
			if (smoke.skipped) {
				pushState(result, "smoke-skipped");
				emit(lines, quiet, `target=${p.id} state=smoke-skipped detail=${smoke.detail}`);
			} else if (smoke.ok) {
				pushState(result, "smoke-ok");
				emit(lines, quiet, `target=${p.id} state=smoke-ok`);
			} else {
				pushState(result, "smoke-failed");
				result.detail = smoke.detail;
				emit(lines, quiet, `target=${p.id} state=smoke-failed detail=${smoke.detail.slice(0, 200)}`);
			}
			targets.push(result);
		} catch (err) {
			const message = err instanceof Error ? err.message : String(err);
			pushState(result, "reconcile-failed");
			result.detail = message;
			emit(lines, quiet, `target=${p.id} state=reconcile-failed detail=error`);
			if (!quiet) process.stderr.write(`error: ${p.id}: ${message}\n`);
			targets.push(result);
		}
	}

	// Success: validated and either smoke-ok or smoke-skipped. Never treat smoke as exact proof.
	const fullyOk = targets.every(
		t => t.states.includes("validated") && (t.status === "smoke-ok" || t.status === "smoke-skipped"),
	);
	emit(lines, quiet, fullyOk ? "result=ok" : "result=failed");
	emit(
		lines,
		quiet,
		"note=per-target states; writes are not rolled back across homes after reconcile begins",
	);
	return { ok: fullyOk, targets, lines };
}

/** List profile ids present under data/home-skills (for diagnostics). */
export function listSkillProfileIds(dataDir: string): string[] {
	const dir = join(dataDir, PROFILE_REL);
	if (!isRealDirectory(dir)) return [];
	return readdirSync(dir)
		.filter(name => !name.startsWith(".") && !name.includes("."))
		.sort();
}
